### ISSUE TITLE
Error clicking the index

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#725]
Hi, when I click on a particular index I have this screen

![image](https://user-images.githubusercontent.com/36895220/46700111-88eb4400-cbe1-11e8-88af-330b03bc231d.png)

I am using OmniDB 2.11.0 and PostgreSQL 10.5

**Comment by wind39** [comment]
Hi @erdusa ,

We just released 2.12.0 with the fix. Would you please try it and give us your valuable feedback, as always? Thanks in advance!

Regards,

William

**Comment by erdusa** [comment]
Hi @wind39, the issue still exists

![image](https://user-images.githubusercontent.com/36895220/47514673-9aba2180-d846-11e8-8612-1b84f0e2ba04.png)

**Comment by wind39** [comment]
Hi @erdusa ,

I managed to reproduce this here with an index with a "WHERE" clause. So I'm assuming this issue is a duplicate of #704 .

I just fixed this, the fix will be out in the next OmniDB release.

Regards,

William

**Comment by erdusa** [comment]
Hi @wind39 

In my case the index doesn't have a where clause, in this case it is not unique

**Comment by wind39** [comment]
Hi @erdusa ,

OmniDB 2.13.0 has a fix which I believe will work on your case. Can you please try and provide your valuable feedback? Thank you!

Regards,

William

**Comment by erdusa** [comment]
Hi @wind39 

This fix works perfectly

Thanks
