### ISSUE TITLE
Monitoring - some units fail on a standby server

### ISSUE THREAD

**Issue by stevenwinfield** [OmniDB/OmniDB#768]
OmniDb  2.12.0, Windows

At least the "Standby: Replication Lag (Size)" and "CPU Usage" units fail to render, giving the error message:

cannot execute CREATE TABLE in a read-only transaction

**Comment by wind39** [comment]
Hi @stevenwinfield ,

Today we released 2.16.0. These monitoring units, when executed against a standby server, will give you an appropriate message.

Keeping this open for a few more days, any feedback would be much appreciated.

Regards,

William

**Comment by stevenwinfield** [comment]
I'm still seeing the "cannot execute CREATE TABLE message"
![image](https://user-images.githubusercontent.com/1327493/63352936-df74f300-c359-11e9-8e81-9693c541734a.png)
