### ISSUE TITLE
SELECT ... INTO is not allowed here

### ISSUE THREAD

**Issue by maerco** [OmniDB/OmniDB#836]
I'm trying to generate a new table with an SQL construct similar to

select 1 into test 

I got the following error:

SELECT ... INTO is not allowed here
LINE 1: ...9c7c421 CURSOR WITH HOLD FOR select 1 into test

`ominidb 2.13.0 - Ubuntu 18.04`

**Comment by wind39** [comment]
Hi @maerco ,

Please let me try to understand better what you need. Is `test` the name of your table?

Because if that's the case, then you need to use `INSERT INTO test SELECT 1`, for example.

Regards,

William

**Comment by maerco** [comment]
Hi @wind39
I would like to use it to create a new table.
Trough pgsql or also pgadmin
I can generate a table with

Create table test as (
Select * from mytable
)

Or more simply as 

Select * into test from mytable

The second option is not working in omnidb

**Comment by wind39** [comment]
Hi @maerco ,

Thanks for explaining. I fixed this, it is going out on next release, 2.15.

Regards,

William

**Comment by maerco** [comment]
Great, thank you

**Comment by wind39** [comment]
Hi @maerco ,

We just released OmniDB 2.15 containing this fix. I'm keeping this open for a few more days in case you want to provide some feedback, which will be much appreciated.

Regards,

William

**Comment by marcofavale** [comment]
Hi @wind39, 

still facing the same issue:

![image](https://user-images.githubusercontent.com/7520748/56414722-ce24b880-628b-11e9-84fa-4208e270a230.png)

**Comment by maerco** [comment]
Hi @wind39 

still facing the same issue

![image](https://user-images.githubusercontent.com/5370848/56415364-d251d580-628d-11e9-9b95-6f15b5186f7f.png)

**Comment by wind39** [comment]
Hi @maerco ,

Unfortunately I can't reproduce this, it works fine for me:

![image](https://user-images.githubusercontent.com/7719686/56426976-90765e80-6290-11e9-87aa-ce63a1540a70.png)

Is there any other details about your test case, please?

Regards,

William

**Comment by wind39** [comment]
Hi @maerco ,

Thanks for the details, you have found the issue indeed. It was working for `INTO` but not for `into`.

Now I have fixed this. The fix will be delivered in the next OmniDB release. I'll keep this open to ping you here again when the next release is out, and hopefully receive your valuable feedback then.

Best regards,

William

**Comment by wind39** [comment]
Hi @maerco ,

Today we released 2.16.0, hopefully settling this issue for good this time. Would you please try it out and confirm?

Thanks in advance.

William

**Comment by maerco** [comment]
Hi @wind39, 

I confirm that the issue is now totally fixed.

Thanks
