### ISSUE TITLE
Unable to change password?

### ISSUE THREAD

**Issue by macmandr197** [OmniDB/OmniDB#869]
Good afternoon everyone,

I've successfully managed to set-up omnidb and have run into an issue. If the admin account sets a user password, the user can log into omnidb with no issues. However, if a user then proceeds to change their password they are then unable to login with either the old password or the new password until the admin account changes their password again. Any suggestions?

**Comment by rafaelthca** [comment]
Hi @macmandr197,

thanks for reporting. Was able to reproduce, unfortunately we introduced this bug after implementing a new feature. Silly bug with disastrous consequences, as it breaks user access.

It is easy to fix and I will do that tomorrow. Do you think you can live with that until the next release, which comes out April 11, or would you like a patched version?

Rafael.

**Comment by macmandr197** [comment]
I appreciate the quick response on your part! While it is a severe bug, I'm okay to wait until the next release :)

**Comment by 47181770** [comment]
How can I fix the bug in my environments?
Many thanks

**Comment by wind39** [comment]
Hi @47181770 ,

We just released OmniDB 2.15 with a fix for this issue. Please update.

After updating, you can use the `omnidb-config` command line utility to create a new OmniDB superuser:

```
omnidb-config -s username password
```

Then login to OmniDB server using this superuser, which will allow you to change the password of all other users via User Management feature, which can be found in the top right corner in OmniDB server web interface (this feature is only enabled to superusers).

Regards,

William

**Comment by wind39** [comment]
Hi @macmandr197 ,

We have just released OmniDB 2.15. Please update. We will keep this issue open for a few more days, in case you want to provide us your valuable feedback about this issue.

Thanks in advance,

William

**Comment by ccurvey** [comment]
this is still broken for me after installed 2.15 over 2.14.  

I seem to be missing an `omnidb-config` command, although I have an `omnidb-config-server` command that looks promising!

```
$ sudo omnidb-config-server -l
+--------+----------+-----------+
| userid | username | superuser |
+--------+----------+-----------+
| 1      | admin    | 1         |
+--------+----------+-----------+
```

Not sure where my old users went, but I'll keep going

```
$ sudo omnidb-config-server -s scooby ruhroh88
Creating superuser...
Superuser created.
```

But when I try tro login with scooby/ruhroh88 (and I copied the password from my command window to the web form), I still get "invalid username or password"

**Comment by wind39** [comment]
Hi @ccurvey ,

`omnidb-config-server` is the same as `omnidb-config`, just installed from the server package.

When you executed `sudo omnidb-config-server -s scooby ...`, then the `scooby` user was probably created in the OmniDB user database `omnidb.db` under your own user `$HOME/.omnidb/omnidb-server/` directory. Which is probably not used if you use `omnidb-server` as root or as the system service.

Please try:

```
sudo su
omnidb-config-server -l
omnidb-config-server -s scooby ...
omnidb-config-server -l
```

To see if the `scooby` OmniDB superuser was actually created. Then try to login as `scooby` in OmniDB.

Best regards,

William

**Comment by ccurvey** [comment]
ah....you are correct @wind39 !  I was trying to figure out where that sqlite database was hidden.

Changing the password for my existing user through the web interface still did not unlock the account.  I ended up deleting the account via the web interface, then adding it back via the command line.

**Comment by wind39** [comment]
Hi @ccurvey ,

So what were the steps you tried? Did you:

1) Create a new superuser with `omnidb-config-server -s username password`;

2) Log into into OmniDB using the new superuser and password you just created;

3) As the new superuser, went to the User Management feature in top-right corner;

4) Changed the password of your existing user there in the grid;

5) Log out of OmniDB;

6) Log in again as your existing user;

7) Optionally drop the temporary superuser you created in step 1.

Is that right?

Regards,

William

**Comment by ccurvey** [comment]
@wind39 yes, that sounds about right.  But at Step 6, I was still not able to log in.   When I deleted the user and then re-added them, I was able to log in.

**Comment by wind39** [comment]
Hi @ccurvey ,

Thanks for explaining. I will investigate that.

Regards,

William
